"""DodanieModeluKsiazka1

Revision ID: a553cba8d46a
Revises: bf66c1ab6013
Create Date: 2025-10-28 11:03:10.261131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a553cba8d46a'
down_revision: Union[str, Sequence[str], None] = 'bf66c1ab6013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ksiazki', sa.Column('polskie_streszczenie', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ksiazki', 'polskie_streszczenie')
    # ### end Alembic commands ###
